stop_loss: [1,2]
limit: [3,5]
sort_mode: True
order:
  B:
    price: open+0.10
    conditions:
      - [pret>0]
      - [pret>0, rmax3 == rmax5]
  S:
    price: [open+0.10, open-0.05]
    conditions:
      - [pret<0]